internal_kb = [

{"id":"kb-001","title":"Processing Online Orders","content":"All online orders must be reviewed in the order management system before packing. Verify payment status and item availability before sending the order to the packing queue."},
{"id":"kb-002","title":"Order Cancellation Requests","content":"Customer service can cancel orders that have not yet entered the packing stage. If the order is already packed, coordinate with the warehouse team before confirming cancellation."},
{"id":"kb-003","title":"Refund Processing","content":"Refunds should be initiated through the finance dashboard. Always verify the original order number and ensure the returned product has been marked as received."},
{"id":"kb-004","title":"Handling Damaged Returns","content":"If a returned product is damaged, document the damage with photos and mark the item in the inventory system as 'damaged return' before escalating to the warehouse manager."},
{"id":"kb-005","title":"Customer Complaint Handling","content":"All customer complaints should be logged in the support system. Include order number, summary of the issue, and any actions taken."},
{"id":"kb-006","title":"Priority Support Tickets","content":"Tickets labeled as 'priority' must be reviewed within 2 hours during business hours. These often involve payment errors or shipment problems."},
{"id":"kb-007","title":"Inventory Restocking","content":"Restocking should be performed every morning before store opening. Employees must scan incoming items to update inventory levels."},
{"id":"kb-008","title":"Low Stock Alerts","content":"Products with inventory below the defined threshold will appear in the low stock dashboard. Purchasing staff should reorder these items within 24 hours."},
{"id":"kb-009","title":"Receiving Supplier Shipments","content":"When supplier shipments arrive, verify the packing list and inspect the items for damage before updating the warehouse inventory system."},
{"id":"kb-010","title":"Product Labeling","content":"All new products must be labeled with SKU, price tag, and category before being placed on store shelves."},

{"id":"kb-011","title":"Price Adjustments","content":"Price changes must be approved by the store manager before being applied to the system and shelf labels."},
{"id":"kb-012","title":"Handling Pre-Orders","content":"Pre-order products must be separated from regular inventory and stored in the pre-order shelf until the official release date."},
{"id":"kb-013","title":"Gift Card Redemption","content":"Gift cards can be redeemed online or in-store. Employees should verify the card balance in the POS system before completing the transaction."},
{"id":"kb-014","title":"POS System Login","content":"Each employee must log in using their personal credentials. Shared accounts are not permitted."},
{"id":"kb-015","title":"End of Day Cash Register","content":"At closing time, the cashier must count the cash drawer and reconcile it with the POS report."},
{"id":"kb-016","title":"Handling Fraud Suspicion","content":"If an order appears fraudulent, flag it in the system and notify the finance team before shipping the order."},
{"id":"kb-017","title":"Shipping Label Printing","content":"Shipping labels should be generated through the order management system to ensure correct tracking numbers."},
{"id":"kb-018","title":"Lost Package Procedure","content":"If a package is reported lost, verify the tracking number and open an investigation with the shipping carrier."},
{"id":"kb-019","title":"Customer Loyalty Points","content":"Customers earn loyalty points for each purchase. Points should automatically update after order completion."},
{"id":"kb-020","title":"Employee Discounts","content":"Employees receive a discount on most products. The discount must be applied using the employee code at checkout."},

{"id":"kb-021","title":"Opening Store Procedure","content":"The opening employee must unlock the store, turn on lights, check the POS system, and verify the store is clean before opening."},
{"id":"kb-022","title":"Closing Store Procedure","content":"Before leaving, employees must turn off lights, secure inventory areas, and ensure the alarm system is activated."},
{"id":"kb-023","title":"Handling Customer Returns","content":"Returns must include proof of purchase. Verify the product condition before processing the return."},
{"id":"kb-024","title":"Workshop Event Setup","content":"Workshop materials should be prepared one hour before the event begins."},
{"id":"kb-025","title":"Workshop Instructor Guidelines","content":"Instructors must provide a safety briefing and ensure all participants have the required tools."},
{"id":"kb-026","title":"Customer Account Assistance","content":"If customers cannot log in, support staff can send a password reset link through the admin panel."},
{"id":"kb-027","title":"Product Category Updates","content":"New product categories must be approved by the product manager before being added to the catalog."},
{"id":"kb-028","title":"Website Product Updates","content":"Product descriptions and images must be updated in the product management system."},
{"id":"kb-029","title":"Handling Supplier Delays","content":"If a supplier shipment is delayed, update the expected delivery date in the inventory system."},
{"id":"kb-030","title":"Reporting System Bugs","content":"All technical issues must be reported in the internal issue tracker with clear reproduction steps."},

{"id":"kb-031","title":"Holiday Sales Preparation","content":"Prepare promotional displays and verify discount codes before the sale begins."},
{"id":"kb-032","title":"Marketing Campaign Setup","content":"Marketing campaigns must be scheduled in advance and approved by the marketing manager."},
{"id":"kb-033","title":"Customer Data Privacy","content":"Employees must not share customer information outside authorized systems."},
{"id":"kb-034","title":"Password Security","content":"Passwords must be at least 12 characters and changed every 90 days."},
{"id":"kb-035","title":"Two Factor Authentication","content":"All internal systems require two-factor authentication for login."},
{"id":"kb-036","title":"Handling Online Reviews","content":"Customer service staff may respond to reviews using approved response templates."},
{"id":"kb-037","title":"Product Photography","content":"New products should be photographed in the studio area before being listed online."},
{"id":"kb-038","title":"Packaging Standards","content":"Fragile hobby items must be packed with bubble wrap and protective inserts."},
{"id":"kb-039","title":"Shipping Insurance","content":"Orders above a defined value threshold must include shipping insurance."},
{"id":"kb-040","title":"Inventory Audits","content":"Warehouse staff must perform a full inventory audit once per quarter."},

{"id":"kb-041","title":"Customer Email Responses","content":"Support emails should be answered within one business day."},
{"id":"kb-042","title":"Internal Communication Tools","content":"Employees should use the company messaging platform for daily communication."},
{"id":"kb-043","title":"Escalating Customer Issues","content":"If an issue cannot be resolved within one interaction, escalate it to the support manager."},
{"id":"kb-044","title":"Managing Backorders","content":"Backordered items should remain in the system until stock arrives."},
{"id":"kb-045","title":"Shipping Address Changes","content":"Address changes can be made only if the order has not yet shipped."},
{"id":"kb-046","title":"Packaging Fragile Models","content":"Model kits with delicate parts must be double boxed."},
{"id":"kb-047","title":"Supplier Contact Protocol","content":"All supplier communication should be documented in the purchasing system."},
{"id":"kb-048","title":"Receiving Returns","content":"Returned packages must be opened and inspected within 24 hours."},
{"id":"kb-049","title":"Damaged Inventory Reporting","content":"Any damaged inventory must be logged immediately."},
{"id":"kb-050","title":"Store Display Maintenance","content":"Displays should be checked daily to ensure products are organized."},

{"id":"kb-051","title":"Product Bundles","content":"Bundle products must be assembled before being listed for sale."},
{"id":"kb-052","title":"Handling Large Orders","content":"Orders containing more than 10 items should be verified before packing."},
{"id":"kb-053","title":"Handling Customer Suggestions","content":"Suggestions should be logged and reviewed during monthly meetings."},
{"id":"kb-054","title":"Supplier Invoice Verification","content":"Invoices must be checked against delivery records."},
{"id":"kb-055","title":"Stock Transfers","content":"Stock transfers between stores must be recorded in the inventory system."},
{"id":"kb-056","title":"Product Safety Guidelines","content":"Ensure all hobby chemicals and paints follow safety regulations."},
{"id":"kb-057","title":"Event Registration","content":"Customers can register for events through the website."},
{"id":"kb-058","title":"Training New Employees","content":"New employees should complete onboarding training within the first week."},
{"id":"kb-059","title":"Handling Customer Feedback","content":"Feedback should be categorized and reviewed monthly."},
{"id":"kb-060","title":"Inventory Shelf Organization","content":"Items must be stored according to category and SKU order."},

{"id":"kb-061","title":"Tracking Warehouse Tasks","content":"Warehouse tasks should be updated in the task management system."},
{"id":"kb-062","title":"Internal Documentation","content":"All internal procedures should be documented in the knowledge base."},
{"id":"kb-063","title":"Email Signature Standards","content":"Employees must use the standard company email signature."},
{"id":"kb-064","title":"Internal Meeting Notes","content":"Meeting summaries should be shared with relevant teams."},
{"id":"kb-065","title":"Handling Urgent Orders","content":"Urgent orders should be prioritized in the packing queue."},
{"id":"kb-066","title":"Label Printer Maintenance","content":"Label printers must be cleaned weekly."},
{"id":"kb-067","title":"Store Cleanliness","content":"Employees must keep the store floor clean and organized."},
{"id":"kb-068","title":"Handling Defective Products","content":"Defective items must be removed from inventory."},
{"id":"kb-069","title":"Inventory Barcode Scanning","content":"Always scan barcodes when moving items in inventory."},
{"id":"kb-070","title":"Customer Wait Time","content":"Customer inquiries should be acknowledged quickly."},

{"id":"kb-071","title":"Store Music Policy","content":"Background music should be kept at a moderate level."},
{"id":"kb-072","title":"Product Demonstrations","content":"Demonstrations should follow safety guidelines."},
{"id":"kb-073","title":"Internal Announcements","content":"Announcements should be posted in the employee portal."},
{"id":"kb-074","title":"Weekly Sales Report","content":"Managers must review weekly sales metrics."},
{"id":"kb-075","title":"Stockroom Safety","content":"Heavy items should be stored on lower shelves."},
{"id":"kb-076","title":"Handling Product Recalls","content":"Immediately remove recalled products from shelves."},
{"id":"kb-077","title":"Shipping Carrier Contacts","content":"Carrier contact info is stored in the logistics dashboard."},
{"id":"kb-078","title":"Handling Holiday Returns","content":"Holiday return deadlines may be extended."},
{"id":"kb-079","title":"Packaging Supplies","content":"Warehouse staff must monitor packaging supply levels."},
{"id":"kb-080","title":"Daily Sales Check","content":"Daily sales reports should be reviewed each morning."},

{"id":"kb-081","title":"Customer Greeting","content":"Employees should greet customers when they enter the store."},
{"id":"kb-082","title":"Handling Refund Disputes","content":"Escalate disputes to the support manager."},
{"id":"kb-083","title":"Store Security Cameras","content":"Cameras should remain active at all times."},
{"id":"kb-084","title":"Emergency Procedures","content":"Follow emergency evacuation plans posted in the store."},
{"id":"kb-085","title":"Handling Online Chat Support","content":"Chat responses should be concise and helpful."},
{"id":"kb-086","title":"Product Knowledge Training","content":"Employees should stay updated on popular hobby products."},
{"id":"kb-087","title":"Warehouse Temperature Control","content":"Maintain stable conditions for sensitive materials."},
{"id":"kb-088","title":"Supplier Quality Issues","content":"Report quality problems to the purchasing manager."},
{"id":"kb-089","title":"Handling High Demand Products","content":"Limit quantities per customer if required."},
{"id":"kb-090","title":"End of Month Reports","content":"Finance compiles reports based on sales data."},

{"id":"kb-091","title":"Store WiFi Access","content":"Employee WiFi credentials should not be shared."},
{"id":"kb-092","title":"Handling Media Requests","content":"Refer all media inquiries to the marketing department."},
{"id":"kb-093","title":"Customer Photo Permissions","content":"Ask permission before using customer photos in marketing."},
{"id":"kb-094","title":"Inventory Disposal","content":"Unsellable items must be disposed of according to policy."},
{"id":"kb-095","title":"Internal Surveys","content":"Employees may be asked to complete internal feedback surveys."},
{"id":"kb-096","title":"Managing Event Supplies","content":"Event materials should be stored separately."},
{"id":"kb-097","title":"Updating Store Signage","content":"Outdated promotional signs should be replaced."},
{"id":"kb-098","title":"Reporting Workplace Issues","content":"Report workplace issues to HR immediately."},
{"id":"kb-099","title":"Weekly Team Meetings","content":"Teams meet weekly to review operations."},
{"id":"kb-100","title":"Knowledge Base Updates","content":"Employees should suggest updates when procedures change."},
{"id":"kb-101","title":"om Slay er et ord","content":"Ja! Slay er et ord, og alle ansatte må bruke slay."}

]

# internal_kb = [

# {"id":"kb-001","title":"Behandling av nettbestillinger","content":"Alle nettbestillinger må gjennomgås i ordrehåndteringssystemet før pakking. Bekreft betalingsstatus og tilgjengelighet av varer før bestillingen sendes til pakkekøen."},
# {"id":"kb-002","title":"Forespørsler om ordreavbestilling","content":"Kundeservice kan avbestille ordre som ennå ikke har kommet til pakkestadium. Hvis ordren allerede er pakket, koordiner med lagerteamet før avbestillingen bekreftes."},
# {"id":"kb-003","title":"Behandling av refusjoner","content":"Refusjoner skal igangsettes gjennom finanspanelet. Bekreft alltid det opprinnelige ordrenummeret og sørg for at returnert produkt er registrert som mottatt."},
# {"id":"kb-004","title":"Håndtering av skadede returer","content":"Hvis et returnert produkt er skadet, dokumenter skaden med bilder og merk varen i lagerstyringssystemet som 'skadet retur' før saken eskaleres til lagerleder."},
# {"id":"kb-005","title":"Håndtering av kundeklager","content":"Alle kundeklager skal registreres i supportsystemet. Inkluder ordrenummer, sammendrag av problemet og eventuelle tiltak som er utført."},
# {"id":"kb-006","title":"Prioriterte supporthenvendelser","content":"Henvendelser merket som 'prioritet' må gjennomgås innen 2 timer i arbeidstiden. Disse gjelder ofte betalingsfeil eller leveringsproblemer."},
# {"id":"kb-007","title":"Påfyll av lager","content":"Påfylling skal utføres hver morgen før butikkåpning. Ansatte må skanne innkommende varer for å oppdatere lagerbeholdningen."},
# {"id":"kb-008","title":"Varsler om lav lagerbeholdning","content":"Produkter med lagerbeholdning under definert terskel vises i lav-lager dashboard. Innkjøpsansatte bør bestille disse varene innen 24 timer."},
# {"id":"kb-009","title":"Mottak av leverandørforsendelser","content":"Når leverandørforsendelser ankommer, bekreft pakkelisten og kontroller varene for skader før lagerbeholdningen oppdateres."},
# {"id":"kb-010","title":"Produktmerking","content":"Alle nye produkter må merkes med SKU, prisetikett og kategori før de plasseres i butikkhyllene."},

# {"id":"kb-011","title":"Prisjusteringer","content":"Prisendringer må godkjennes av butikksjef før de legges inn i systemet og på hylleetiketter."},
# {"id":"kb-012","title":"Håndtering av forhåndsbestillinger","content":"Forhåndsbestilte produkter må holdes atskilt fra vanlig lager og lagres på forhåndsbestillingshylle til offisiell utgivelsesdato."},
# {"id":"kb-013","title":"Innløsning av gavekort","content":"Gavekort kan innløses online eller i butikk. Ansatte bør sjekke saldo i kassesystemet før transaksjonen fullføres."},
# {"id":"kb-014","title":"Innlogging i POS-system","content":"Hver ansatt må logge inn med sine personlige tilgangsopplysninger. Delte kontoer er ikke tillatt."},
# {"id":"kb-015","title":"Dagens kasseoppgjør","content":"Ved stengetid må kassereren telle kassen og avstemme med POS-rapporten."},
# {"id":"kb-016","title":"Håndtering av mistanke om svindel","content":"Hvis en ordre virker mistenkelig, merk den i systemet og informer økonomiteamet før ordren sendes."},
# {"id":"kb-017","title":"Utskrift av fraktetiketter","content":"Fraktetiketter skal genereres via ordrehåndteringssystemet for å sikre korrekt sporingsnummer."},
# {"id":"kb-018","title":"Fremgangsmåte ved tapte pakker","content":"Hvis en pakke rapporteres tapt, bekreft sporingsnummer og start etterforskning med transportøren."},
# {"id":"kb-019","title":"Kundelojalitetspoeng","content":"Kunder opptjener poeng for hvert kjøp. Poengene skal oppdateres automatisk etter fullført ordre."},
# {"id":"kb-020","title":"Ansattrabatter","content":"Ansatte får rabatt på de fleste produkter. Rabatten må brukes med ansattkode ved kassen."},

# {"id":"kb-021","title":"Åpning av butikk","content":"Ansatte som åpner butikken må låse opp døren, slå på lys, sjekke POS-systemet og sikre at butikken er ren før åpning."},
# {"id":"kb-022","title":"Stenging av butikk","content":"Før ansatte forlater butikken, må lys slås av, lagerområder sikres, og alarmsystem aktiveres."},
# {"id":"kb-023","title":"Håndtering av kundeturer","content":"Returer må inkludere kjøpsbevis. Kontroller produktets tilstand før returen behandles."},
# {"id":"kb-024","title":"Forberedelse til workshop","content":"Workshopmaterialer skal være klare en time før arrangementet begynner."},
# {"id":"kb-025","title":"Retningslinjer for workshopinstruktører","content":"Instruktører må gi sikkerhetsinstruks og sikre at alle deltakere har nødvendige verktøy."},
# {"id":"kb-026","title":"Kundekontoassistanse","content":"Hvis kunder ikke kan logge inn, kan support sende en link for tilbakestilling av passord via administrasjonspanelet."},
# {"id":"kb-027","title":"Oppdatering av produktkategorier","content":"Nye produktkategorier må godkjennes av produktansvarlig før de legges til katalogen."},
# {"id":"kb-028","title":"Oppdatering av produkter på nettside","content":"Produktbeskrivelser og bilder må oppdateres i produktstyringssystemet."},
# {"id":"kb-029","title":"Håndtering av leverandørforsinkelser","content":"Hvis en leveranse er forsinket, oppdater forventet levering i lagersystemet."},
# {"id":"kb-030","title":"Rapportering av systemfeil","content":"Alle tekniske problemer skal rapporteres i intern issue tracker med tydelige gjenskapingstrinn."},

# {"id":"kb-031","title":"Forberedelse til høytidssalg","content":"Forbered kampanjeutstillinger og bekreft rabattkoder før salget starter."},
# {"id":"kb-032","title":"Oppsett av markedsføringskampanjer","content":"Markedsføringskampanjer må planlegges på forhånd og godkjennes av markedsføringsleder."},
# {"id":"kb-033","title":"Personvern for kundedata","content":"Ansatte må ikke dele kundeinformasjon utenfor autoriserte systemer."},
# {"id":"kb-034","title":"Passordsikkerhet","content":"Passord må være minst 12 tegn og endres hver 90. dag."},
# {"id":"kb-035","title":"To-faktor autentisering","content":"Alle interne systemer krever to-faktor autentisering ved innlogging."},
# {"id":"kb-036","title":"Håndtering av nettanmeldelser","content":"Kundeservice kan svare på anmeldelser med godkjente maler."},
# {"id":"kb-037","title":"Produktfotografering","content":"Nye produkter bør fotograferes i studio før de legges ut på nettet."},
# {"id":"kb-038","title":"Emballeringsstandarder","content":"Skjøre hobbyartikler må pakkes med bobleplast og beskyttende innlegg."},
# {"id":"kb-039","title":"Fraktforsikring","content":"Ordre over definert verdi må inkludere fraktforsikring."},
# {"id":"kb-040","title":"Lagerrevisjon","content":"Lagerpersonell må utføre full lagerrevisjon kvartalsvis."},

# {"id":"kb-041","title":"Svar på kundemail","content":"Support-e-poster skal besvares innen én arbeidsdag."},
# {"id":"kb-042","title":"Interne kommunikasjonsverktøy","content":"Ansatte bør bruke selskapets meldingsplattform til daglig kommunikasjon."},
# {"id":"kb-043","title":"Eskalering av kundesaker","content":"Hvis et problem ikke løses i én interaksjon, eskaler det til supportleder."},
# {"id":"kb-044","title":"Håndtering av restordre","content":"Restordre varer skal forbli i systemet til lager er på plass."},
# {"id":"kb-045","title":"Endring av leveringsadresse","content":"Adresseendringer kan kun gjøres hvis ordren ikke er sendt."},
# {"id":"kb-046","title":"Emballering av skjøre modeller","content":"Modellsatser med delikate deler må dobbel-pakkes."},
# {"id":"kb-047","title":"Leverandørkontaktprotokoll","content":"All kommunikasjon med leverandør skal dokumenteres i innkjøpssystemet."},
# {"id":"kb-048","title":"Mottak av returer","content":"Returnerte pakker må åpnes og kontrolleres innen 24 timer."},
# {"id":"kb-049","title":"Rapportering av skadet lager","content":"Alt skadet lager må registreres umiddelbart."},
# {"id":"kb-050","title":"Vedlikehold av butikkdisplay","content":"Displayene skal sjekkes daglig for å sikre at produktene er organisert."},

# {"id":"kb-051","title":"Produktpakker","content":"Pakkeprodukter må monteres før de legges ut for salg."},
# {"id":"kb-052","title":"Håndtering av store ordre","content":"Ordre med mer enn 10 varer skal verifiseres før pakking."},
# {"id":"kb-053","title":"Håndtering av kundeforslag","content":"Forslag skal registreres og gjennomgås under månedlige møter."},
# {"id":"kb-054","title":"Leverandørfakturasjekk","content":"Fakturaer må kontrolleres mot leveringsdokumenter."},
# {"id":"kb-055","title":"Vareoverføringer","content":"Vareoverføringer mellom butikker må registreres i lagersystemet."},
# {"id":"kb-056","title":"Produktsikkerhetsretningslinjer","content":"Sørg for at alle hobbykjemikalier og maling følger sikkerhetsregler."},
# {"id":"kb-057","title":"Arrangementregistrering","content":"Kunder kan registrere seg til arrangementer via nettsiden."},
# {"id":"kb-058","title":"Opplæring av nye ansatte","content":"Nye ansatte bør fullføre onboarding-trening i løpet av første uke."},
# {"id":"kb-059","title":"Håndtering av kundetilbakemeldinger","content":"Tilbakemeldinger skal kategoriseres og gjennomgås månedlig."},
# {"id":"kb-060","title":"Organisering av lagerhyller","content":"Varer må lagres etter kategori og SKU-rekkefølge."},

# {"id":"kb-061","title":"Sporing av lageroppgaver","content":"Lageroppgaver skal oppdateres i oppgavestyringssystemet."},
# {"id":"kb-062","title":"Intern dokumentasjon","content":"Alle interne prosedyrer skal dokumenteres i kunnskapsbasen."},
# {"id":"kb-063","title":"Standard for e-postsignaturer","content":"Ansatte må bruke selskapets standard e-postsignatur."},
# {"id":"kb-064","title":"Møteprotokoller","content":"Møtesammendrag skal deles med relevante team."},
# {"id":"kb-065","title":"Håndtering av hasteordrer","content":"Hasteordrer skal prioriteres i pakkekøen."},
# {"id":"kb-066","title":"Vedlikehold av etikettprintere","content":"Etikettprintere må rengjøres ukentlig."},
# {"id":"kb-067","title":"Renhold i butikken","content":"Ansatte må holde butikklokalet rent og ryddig."},
# {"id":"kb-068","title":"Håndtering av defekte produkter","content":"Defekte varer må fjernes fra lageret."},
# {"id":"kb-069","title":"Skanning av strekkoder i lageret","content":"Alltid skann strekkoder ved flytting av varer i lageret."},
# {"id":"kb-070","title":"Kundetid","content":"Kundehenvendelser skal besvares raskt."},

# {"id":"kb-071","title":"Musikkpolicy i butikk","content":"Bakgrunnsmusikk skal holdes på moderat nivå."},
# {"id":"kb-072","title":"Produktdemonstrasjoner","content":"Demonstrasjoner skal følge sikkerhetsretningslinjer."},
# {"id":"kb-073","title":"Interne kunngjøringer","content":"Kunngjøringer skal publiseres i ansattportalen."},
# {"id":"kb-074","title":"Ukentlig salgsrapport","content":"Ledere må gjennomgå ukentlige salgsdata."},
# {"id":"kb-075","title":"Sikkerhet i lagerrom","content":"Tunge varer bør plasseres på nedre hyller."},
# {"id":"kb-076","title":"Håndtering av produkttilbakekallinger","content":"Umiddelbart fjern tilbakekalte produkter fra hyllene."},
# {"id":"kb-077","title":"Transportørkontakter","content":"Transportørinformasjon lagres i logistikksystemet."},
# {"id":"kb-078","title":"Håndtering av høytidsreturer","content":"Returfrister i høytiden kan forlenges."},
# {"id":"kb-079","title":"Emballeringsmaterialer","content":"Lagerpersonell må overvåke nivåer på emballasjemateriell."},
# {"id":"kb-080","title":"Daglig salgsoversikt","content":"Daglige salgsrapporter skal gjennomgås hver morgen."},

# {"id":"kb-081","title":"Møt kunder","content":"Ansatte bør hilse på kunder når de entrer butikken."},
# {"id":"kb-082","title":"Håndtering av refusjonskonflikter","content":"Eskalér konflikter til supportleder."},
# {"id":"kb-083","title":"Butikkens sikkerhetskameraer","content":"Kameraer skal være aktive til enhver tid."},
# {"id":"kb-084","title":"Nødprosedyrer","content":"Følg evakueringsplaner som er oppslått i butikken."},
# {"id":"kb-085","title":"Håndtering av nett-chat support","content":"Chat-svar skal være korte og hjelpsomme."},
# {"id":"kb-086","title":"Produktkunnskapstrening","content":"Ansatte bør holde seg oppdatert på populære hobbyprodukter."},
# {"id":"kb-087","title":"Temperaturkontroll i lager","content":"Oppretthold stabile forhold for sensitive materialer."},
# {"id":"kb-088","title":"Kvalitetsproblemer hos leverandør","content":"Rapporter kvalitetsproblemer til innkjøpsansvarlig."},
# {"id":"kb-089","title":"Håndtering av produkter med høy etterspørsel","content":"Begrens antall per kunde hvis nødvendig."},
# {"id":"kb-090","title":"Slutten av månedsrapporter","content":"Økonomiavdelingen utarbeider rapporter basert på salgsdata."},

# {"id":"kb-091","title":"Tilgang til butikkens WiFi","content":"Ansattes WiFi-tilgang skal ikke deles."},
# {"id":"kb-092","title":"Håndtering av mediehenvendelser","content":"Henvis alle mediehenvendelser til markedsavdelingen."},
# {"id":"kb-093","title":"Tillatelse for kundebilder","content":"Spør om tillatelse før bruk av kundebilder i markedsføring."},
# {"id":"kb-094","title":"Kassering av lager","content":"Usalgbare varer må kasseres i henhold til policy."},
# {"id":"kb-095","title":"Interne undersøkelser","content":"Ansatte kan bli bedt om å fylle ut interne tilbakemeldingsundersøkelser."},
# {"id":"kb-096","title":"Håndtering av arrangementsutstyr","content":"Arrangementsmateriell skal lagres separat."},
# {"id":"kb-097","title":"Oppdatering av butikkens skilting","content":"Utdaterte kampanjeskilt skal byttes ut."},
# {"id":"kb-098","title":"Rapportering av arbeidsplassproblemer","content":"Rapporter arbeidsplassproblemer til HR umiddelbart."},
# {"id":"kb-099","title":"Ukentlige teammøter","content":"Teamene møtes ukentlig for å gjennomgå drift."},
# {"id":"kb-100","title":"Oppdatering av kunnskapsbase","content":"Ansatte bør foreslå oppdateringer når prosedyrer endres."}

# ]